title:              PlumBuggle68
tagline:            The One and Only
description:        PlumBuggleWebsite...
url:                http://YourName.github.io

author:
  name:             PlumBuggle68
  url:              https://x.com/plumbuggle68
  email:            n/a

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
